name: Cleanup Posts and Conversations

on:
  schedule:
    - cron: '0 3 * * 0'  # Run at 3 AM UTC every Sunday (once per week)
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: 'dtac4dhtj'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd .github/scripts
          npm init -y
          npm install typescript ts-node @types/node
          npm install @supabase/supabase-js cloudinary
          echo '{
            "compilerOptions": {
              "target": "es2018",
              "module": "commonjs",
              "strict": true,
              "esModuleInterop": true,
              "skipLibCheck": true,
              "forceConsistentCasingInFileNames": true,
              "outDir": "./dist"
            },
            "include": ["./**/*.ts"],
            "exclude": ["node_modules"]
          }' > tsconfig.json

      - name: Run cleanup scripts
        run: |
          cd .github/scripts
          npx ts-node cleanupConversations.ts
          npx ts-node cleanupPosts.ts 