name: Cleanup Expired Posts

on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3 AM UTC daily
  workflow_dispatch:      # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    env:
      EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
      EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install @supabase/supabase-js
          npm install node-fetch

      - name: Run cleanup script
        run: |
          node -e "
            const { cleanupExpiredPosts } = require('./.github/scripts/cleanup.js');
            
            async function runCleanup() {
              const result = await cleanupExpiredPosts();
              if (!result.success) {
                console.error('Cleanup failed:', result.error);
                process.exit(1);
              }
              console.log('Cleanup succeeded:', result);
            }
            
            runCleanup();
          "